version: "3.8"
services:
  client:
    build:
      context: ./client
      dockerfile: dockerfile
    ports:
      - 5173:5173
    environment:
      - SERVER_URL=${SERVER_URL}
    depends_on:
      - server
    
  server:
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - 8000:8000
    environment:
      - BROWSER_PATH=${BROWSER_PATH}
      - DATA_DIR=${DATA_DIR}
